### ISSUE TITLE
0.1 version missing in repo

### ISSUE THREAD

**Issue by wociscz** [zabbly/incus#11]
(not an issue I think)
Hi, I just noticed that latest `0.1` version disappeared from the repository (stable). 
Seems like you are keeping only the two newest versions.
Regarding to https://github.com/lxc/incus/issues/218 I'm not able to install working version. I can handle it with the transfer packages from other servers or using aptly to keep the versions cached. But looks like sub-optimal solution.

**Comment by stgraber** [comment]
I'll be cherry-picking that particular fix into the 0.2 package which should then fix things for you.

**Comment by stgraber** [comment]
Pushed the cherry-pick now, a fixed package should be available in the next few hours

**Comment by stgraber** [comment]
Updated packages available now.

**Comment by wociscz** [comment]
Spectacular! Really thanks!
