### ISSUE TITLE
incus cannot be installed inside a container

### ISSUE THREAD

**Issue by antifob** [zabbly/incus#12]
`incus`'s `postinst` script has the following line which blocks installation of `incus` inside a container:

```
systemctl reload incus-lxcfs.service
```

This is caused by the following line in `incus-lxcfs.service`:

```
ConditionVirtualization=!container
```

Removing the above line allows the package to be installed.

It is unclear to me why `incus-lxcfs.service` shouldn't be running inside a container.

**Comment by stgraber** [comment]
That's because LXCFS should only ever run on the host, inside containers it should just pass through what it gets from the host.

I suspect we just need a modification to the packaging scripts to ignore errors on lxcfs.
