### ISSUE TITLE
Consider creating `incus` system user as part of package

### ISSUE THREAD

**Issue by f-bn** [zabbly/incus#14]
Hello,

During some tests of these packages, I could see that there is some groups created for Incus, but there is no `incus` system user created for sub-processes such as dnsmasq or QEMU. Therefore, these processes uses `nobody` user for their exec, I was a bit surprised at first coming from LXD where there is a native `lxd` user. After looking in the Incus source code, `nobody` user is indeed used if there is no `incus` user present on the system. In fact, I think this doesn't change anything, I just think this is a bit cleaner from a system administration perspective.

WDYT ? I can prepare a PR if needed :)

**Comment by stgraber** [comment]
Ah yeah, that'd absolutely make sense, a PR would be very much appreciated!

**Comment by f-bn** [comment]
Alright, I will send a PR soon :)

**Comment by stgraber** [comment]
Thanks!

**Comment by ghost** [comment]
Will people who installed Incus before [this commit](https://github.com/zabbly/incus/pull/16) have to create the user manually or will a package upgrade do this?

**Comment by stgraber** [comment]
The package update will do it
