### ISSUE TITLE
Unable to use xtables due to hard dependency on nftables

### ISSUE THREAD

**Issue by gianfurrer** [zabbly/incus#29]
I'm currently trying to switch from LXD to Incus. I am still depending on the `xtables` firewall.

Since [this commit](https://github.com/zabbly/incus/commit/c2696228418ab06f39d0c218fc39c1efe54d9e45), `nftables` seems to be a hard dependency.  And since `nftables` seems to  get prioritized over `xtables` (according to [this code](https://github.com/lxc/incus/blob/0d5f33f13875c6611826ff498c9be2545f991027/internal/server/firewall/firewall_load.go#L17)) I don't see a way to make incus use the `xtables` firewall anymore:

```bash
incus info | grep firewall
- network_firewall_filtering
- firewall_driver
  firewall: nftables
```

Is this intentional? And if so, is there a way to still depend on `xtables` as firewall in Incus?

**Comment by stgraber** [comment]
Incus will use xtables if xtables is detected to already have some rules loaded at the time Incus starts.

But not that this is only true if your system uses the real xtables. Both Debian and Ubuntu default to having xtables drive nft behind the scenes.

**Comment by gianfurrer** [comment]
I assume with real xtables you  mean `iptables-legacy` instead of `iptables-nft`? If so, then that is the case in my scenario. 

> Incus will use xtables if xtables is detected to already have some rules loaded at the time Incus starts.

I just reinstalled incus while making sure that I have xtables entries and now it actually uses `xtables`, so thanks for that!

But is it still possible to have `nftables` as an optional dependency again? I don't see a reason to have it installed when depending on `xtables` and it also wasn't necessary in the past. 

Additionally, https://packages.ubuntu.com/noble/incus also still mentions that either `nftables` or `iptables` is required.
