### ISSUE TITLE
incus UI

### ISSUE THREAD

**Issue by osamuaoki** [zabbly/incus#31]
Dialog displayed by `CertificateGenerate-8ae719bf.js` has:

```
"incus config trust add-certificate Downloads/incus-ui.crt"
```
But what I downloaded was `incus-ui-localhost.crt`.

So shouldn't it more or less like:
```
"incus config trust add-certificate Downloads/incus-ui-localhost.crt"
```

As I see javascript, the downloaded file name seems to be coming from:
```
{onClick:()=>I(`incus-ui-${location.hostname}.crt`,t.crt)
```
Maybe these 2 should use the same name.

FYI: I am not javascript person.

**Comment by stgraber** [comment]
Yeah, we can change the example command so it matches more folks.
