### ISSUE TITLE
lxd-to-incus: present in both incus-tools and incus-base

### ISSUE THREAD

**Issue by antifob** [zabbly/incus#34]
Hi,

I wanted to try out `incus-simplestreams`. To do so, I upgraded the core packages (incus-base and incus-client) to incus 0.7 and attempted to install `incus-tools`, but it fails due to `/usr/bin/lxd-to-incus` being already provided by `incus-base`.

```
# apt-get -y install incus-tools
...
Unpacking incus-tools (0.7-1) ...
dpkg: error processing archive /var/cache/apt/archives/incus-tools_0.7-1_amd64.deb (--unpack):
 trying to overwrite '/usr/bin/lxd-to-incus', which is also in package incus-base 0.7-202403261638-debian12
...
# dpkg -L incus-base | grep lxd-to-incus
/opt/incus/bin/lxd-to-incus
/usr/bin/lxd-to-incus
# apt-file show incus-tools | grep lxd-to-incus
incus-tools: /usr/bin/lxd-to-incus
incus-tools: /usr/share/man/man1/lxd-to-incus.1.gz
```

**Comment by stgraber** [comment]
`incus-tools` here comes from Debian, not from this repository.

The new `incus-extra` package which will contain the simplestreams tool hasn't been published yet.
