### ISSUE TITLE
lxcfs.loadavg

### ISSUE THREAD

**Issue by janmuennich** [zabbly/incus#40]
Is there an option to set which was `snap set lxd lxcfs.loadavg=true`?

I only found this post which hinted that it hasn't been done yet: https://discuss.linuxcontainers.org/t/lxd-snap-incus-migration/19114/2

If there is no config option yet, what would be the recommended workaround?

**Comment by stgraber** [comment]
You can configure `/etc/default/incus`

**Comment by janmuennich** [comment]
Thanks! Don't know why I didn't find that myself.
