### ISSUE TITLE
Web UI - OIDC Issue

### ISSUE THREAD

**Issue by ThinkFar** [zabbly/incus#45]
Hello! 

I have Incus OIDC set up with Keycloak. This configuration has been working well for a while, but now (update?) when I click the login SSO button, it gets stuck on the /oidc/login page. There are no URL parameters, no body content, and no errors to debug. It just shows an empty page and doesn't continue redirecting me to the configured OIDC provider.

**Comment by ThinkFar** [comment]
@stgraber and if it is *somehow* possible to disable the built-in login, I would honestly break out in tears. The authentication situation has given me nothing but issues, even in LXD-UI times, due to the setup I'm working with since there are additional security measures in place that make the built-in Incus UI authentication completely obsolete. Maybe by applying some changes to the incus-ui code?

**Comment by roukydesbois** [comment]
Hello,

I think I am facing the same issue, and I see this when running `journalctl -xeu incus` (the timestamp corresponds to the login issue):

```
juil. 13 17:06:18 REDACTED_HOSTNAME incusd[3108957]: time="2024-07-13T17:06:18+01:00" level=warning msg="Rejecting request from untrusted client" ip="REDACTED_IP:40240"
```

I'm also going to investigate on the Keycloak side to see if there is an issue there.

**Comment by stgraber** [comment]
We're not planning on allowing disabling HTTPS authentication Incus.

That said, you do have workarounds you can use, most commonly:
 - Run a proxy going from HTTPS to HTTPS with a hardcoded trusted TLS certificate
 - Run a proxy going from HTTPS to the local unix socket

**Comment by pymen** [comment]
Need to improve instruction for chrome to use
chrome://certificate-manager/clientcerts
