### ISSUE TITLE
`incus top` doesn't properly report disk usage on BTRFS backends

### ISSUE THREAD

**Issue by pieterhollander** [zabbly/incus#47]
I'm using Incus with a BTRFS backend. 
When I run the new `incus top` command on Incus 6.0.1. LTS, disk usage for all containers is reported to be the same, except for my Docker container, which uses a separate storage pool.
Having this report properly would be very useful, especially given the fact that `du` isn't reliable with BTRFS.

<img width="388" alt="Screenshot 2024-07-01 at 10 36 07" src="https://github.com/zabbly/incus/assets/1392118/eb9bc42f-c7e0-4dae-9b56-0650673dbe02">

Additionally, but that would be more of a feature request rather than a bug report, it would be nice to have both a 'physical size' as well as `uncompressed / deduplicated size' column.

**Comment by stgraber** [comment]
What does `incus list -cnD` show you?

**Comment by pieterhollander** [comment]
```sh
incus list -cnD
+--------+------------+
|  NAME  | DISK USAGE |
+--------+------------+
| av     |            |
+--------+------------+
| dns    |            |
+--------+------------+
| docker |            |
+--------+------------+
| hbp    |            |
+--------+------------+
| mdb    |            |
+--------+------------+
| pg     |            |
+--------+------------+
| runner |            |
+--------+------------+
| turn   |            |
+--------+------------+
```

**Comment by pieterhollander** [comment]
BTW, I just realised I opened this issue in zabbly/incus instead of lxc/incus. If this is the wrong location, I'll gladly reopen it over there.

**Comment by stgraber** [comment]
It's the wrong location but that's not really a problem, I look at both :)

Okay, so Incus has no idea what the disk usage is. Does `df -h /` show you the container-specific usage inside the container?

If not, then there's nothing we can do. `incus top` hits every single instance every 5s so we definitely can't run something heavy weight like `du` :)

**Comment by stgraber** [comment]
What we should do though is not show a usage value when we can't figure it out.

**Comment by stgraber** [comment]
Ah but that's because we can't quite figure it out as all we're told by the kernel is:
 - Total space
 - Free space
 - Available space (basically free - some reserved stuff)

So it's not something we can do from the `incus top` side of things. But we may be able to make incus just not return the metric at all in environments where there is no such thing as a container-specific value.
