### ISSUE TITLE
Ubuntu 16.04 can not be started (on Try Incus instance)

### ISSUE THREAD

**Issue by cerebrux** [zabbly/incus#53]
While using the "[try Incus](https://linuxcontainers.org/incus/try-it/)" I tried to create an ubuntu 16.04 instance through Web UI. When using the provided image, it reports that

_The instance was created, but could not be started. The image used by this instance requires a CGroupV1 host system_

![image](https://github.com/user-attachments/assets/5f048ee6-1150-4672-b173-7d89a877604d)

The overview tab:

![image](https://github.com/user-attachments/assets/f63b8d17-e1c0-42af-a990-f6562ffdfa00)

**Comment by stgraber** [comment]
The error is correct, Ubuntu 16.04 containers require a system running CGroup1.
Modern systems run CGroup2 and are therefore unable to run such old Linux distributions.

This did make me realize that we were still building some very old images for Ubuntu which don't really make sense given that they're now unsupported without additional paid support.

The Ubuntu 16.04, 18.04 and 23.10 images will disappear from our image servers over the coming days.
