### ISSUE TITLE
incus-user: Handle missing project but existing network

### ISSUE THREAD

**Issue by boober95** [zabbly/incus#56]
I unintentionally deleted my user project, user-1001, via the UI web interface.  Reading comments online I thought it would get recreated with the next command, but not so.

Logged in as 'user' and using a command to list the images, gets an error as:

incus image list
Error: Get "http://unix.socket/1.0?project=user-1001": read unix @->/var/lib/incus/unix.socket.user: read: connection reset by peer

I tired creating the project via the web interfaces, but that doesn't fix it either, nor does trying other commands such and launching a new container.

Possibly related, the web interface on the bottom left, just above 'Documentation' has an entry like 'dddf0b0...', which is not clickable, it was not there before.

I tried doing an update, but no love, now at version 6.5:

incus --version
6.5

Any suggestions on how I can fix this?

Bill

**Comment by stgraber** [comment]
Make sure to also delete the user bridge network. Incus may be failing to create the project due to the network already existing.

**Comment by boober95** [comment]
Excellent, I deleted the user bridge then the user profile was created as expected.

FYI, I noted minor differences from before (according to my memory):
1) the project was bill-1001 and now it is user-1001,
2) the default network has ipv4 and no ipv6, but user-1001 has both (not sure what it was before), and
3) launching a container results in a container with an ipv6 address and no ipv4 address.

BTW, I still have the weird entry above 'Documentation' in the GUI, it looks like a lock and 'dddf0b0..' that I don't think was there originally. 

Altogether things are working again and I thank you.

Bill

**Comment by boober95** [comment]
A little more info:  I set ipv6 to 'none' similar to the default network, now when I create a container it has neither an ipv4 nor a ipv6 address.

Bill

**Comment by boober95** [comment]
My bad, I forgot I'd setup a firewall along the way (this is a new installation), I found your previous answer here:

https://discuss.linuxcontainers.org/t/container-does-not-get-ipv4-address/19735

Bill

**Comment by stgraber** [comment]
> the project was bill-1001 and now it is user-1001,

It was always named `user-XYZ`, we don't want to risk a username change breaking things.

> the default network has ipv4 and no ipv6, but user-1001 has both (not sure what it was before), and

We don't look at any existing `default` network when creating our per-user networks, so they all get the Incus defaults which are IPv4 and IPv6 connectivity.

> launching a container results in a container with an ipv6 address and no ipv4 address.

That's likely a firewall issue as you've noted in a follow-up comment.

**Comment by stgraber** [comment]
I'll look at fixing the `incus-user` handling so it can deal with an existing network.

Btw, in the future, note that Incus issues are better reported at https://github.com/lxc/incus/isuses
This repository is mostly about the packaging that's done for Debian and Ubuntu.

**Comment by boober95** [comment]
OK, will report issues in the future, thanks again for you help.

Bill

**Comment by stgraber** [comment]
Keeping this open as it's not been addressed yet
