### ISSUE TITLE
broken patch - Source changed: li to SideNavigationItem

### ISSUE THREAD

**Issue by zarac** [zabbly/incus#60]
https://github.com/zabbly/incus/blob/68f7acb33c64cc98b17b41eba12563032a8e232c/patches/ui-canonical-0002-Update-navigation.patch#L22

https://github.com/canonical/lxd-ui/commit/99079c3bdf471d6821c0c75c74e6f4dddf9df526

**Comment by stgraber** [comment]
Not sure what that issue is about. 

If it's the the patches no longer apply to current lxd-ui, then that's fine, we don't patch the current lxd-ui during our builds.

**Comment by stgraber** [comment]
Saw the title now, so yeah, we don't apply our patches in the current version of lxd-ui.

**Comment by zarac** [comment]
@stgraber Alrighty. Thanks!

PS/FYI This was in regards to the AUR build. (It applies the patches, but has for now been kept back to 0.12 in waiting for new patches. There's now a comment there rerferring to here).

**Comment by LevitatingBusinessMan** [comment]
So will the patches be updated to reflect the change in lxd-ui 0.13? And thus will incus-ui-canonical be updated to 0.13? Or will it be kept at version 0.12 for the foreseeable future.

**Comment by stgraber** [comment]
It will eventually be updated to 0.13 but it's not a high priority thing for us.
