### ISSUE TITLE
Size/ipv4/ipv6 filter not clickable in storage pools/volumes/network menu. (GUI)

### ISSUE THREAD

**Issue by Skyridr** [zabbly/incus#61]
I noticed that in instances, IPV4/IPV6 is not clickable to filter, same applied in network menu.
![image](https://github.com/user-attachments/assets/88c6b78f-067f-4b0b-9371-378b95ecbf5e)

Same with size, not clickable in pools and volumes:

![image](https://github.com/user-attachments/assets/0f8d074c-355c-45ed-8be6-520f2e3656f6)
Is this done on purpose by any chance? Or forgot to be included?

Regards,
Skyrider

**Comment by stgraber** [comment]
I'm not sure. That's not code that we've altered from the original LXD UI (https://github.com/canonical/lxd-ui). It does seem like it would make sense to have all columns in tables be sortable, but I don't know if there was a technical reason why this wasn't feasible or if it was a design decision for some reason.

**Comment by stgraber** [comment]
https://github.com/zabbly/incus-ui-canonical/commit/3c9399a0d31cc2c1e0595a1bb006631840d2b7d1
