### ISSUE TITLE
Viewing instance details breaks the web UI

### ISSUE THREAD

**Issue by xorbug** [zabbly/incus#66]
This is probably an upstream issue, hope it's ok to report it here tho.

As per the title, viewing instance details breaks the web UI. This only happens with a couple instances living in a different storage pool than the one defined in their profile (tried with both setting it at creation time or moving the instance to a different storage pool after the creation).

Of course the disk root is defined in the config, and the instances appears to be otherwise fully functional and discoverable via the incus cli.

![image](https://github.com/user-attachments/assets/2b9cc3e9-d3d6-4ea1-877e-29603ff63e7a)

Let me know if more details are needed and thanks for the support.

---

Error transcription for searches:
```
Error

o.disk.root is undefined

Stack trace

Ha@http://localhost:3800/ui/assets/InstanceDetail-Pl4iR06o.js:1:6885
K_@http://localhost:3800/ui/assets/index-B893LGfq.js:39:17000
yg@http://localhost:3800/ui/assets/index-B893LGfq.js:41:3139
jj@http://localhost:3800/ui/assets/index-B893LGfq.js:41:44804
Pj@http://localhost:3800/ui/assets/index-B893LGfq.js:41:39768
JM@http://localhost:3800/ui/assets/index-B893LGfq.js:41:39696
vf@http://localhost:3800/ui/assets/index-B893LGfq.js:41:39547
xg@http://localhost:3800/ui/assets/index-B893LGfq.js:41:35914
nS@http://localhost:3800/ui/assets/index-B893LGfq.js:41:36717
qo@http://localhost:3800/ui/assets/index-B893LGfq.js:39:3274
Zn/<@http://localhost:3800/ui/assets/index-B893LGfq.js:41:34246
```

**Comment by stgraber** [comment]
This has already been fixed.
